Connection - GitHub

In [2]:
import sys
sys.path.append("/content/drive/MyDrive")
import mykeys

project_name = "recsys"
path = "/content/" + project_name
!mkdir "{path}"
%cd "{path}"

import sys
sys.path.append(path)

!git init
!git remote add origin https://"{mykeys.git_token}":x-oauth-basic@github.com/sparsh-ai/"{project_name}".git
!git pull origin main

/content/recsys
Initialized empty Git repository in /content/recsys/.git/
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
From https://github.com/sparsh-ai/recsys
 * branch            main       -> FETCH_HEAD
 * [new branch]      main       -> origin/main


In [62]:
!git add .
!git commit -m 'commit'
!git push origin master

[master a8c7bc7] commit
 2 files changed, 0 insertions(+), 0 deletions(-)
 rename notebooks/{RecSys ML-100K => RecSys ML-100K.ipynb} (100%)
 rename notebooks/{RecSys_AmazonMusic => RecSys_AmazonMusic.ipynb} (100%)
Counting objects: 3, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 281 bytes | 281.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/sparsh-ai/recsys.git
   9dd302b..a8c7bc7  master -> master


In [ ]:
!cp -r /content/drive/MyDrive/Colab\ Notebooks/RecSys* ./notebooks

In [29]:
import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.nn.functional as F

In [23]:
data = pd.read_csv("./data/MovieLens_LatestSmall_ratings.csv.csv")
data.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

Data encoding

In [27]:
np.random.seed(3)
msk = np.random.rand(len(data)) < 0.8
train = data[msk].copy()
valid = data[~msk].copy()

In [25]:
# here is a handy function modified from fast.ai
def proc_col(col, train_col=None):
    """Encodes a pandas column with continous ids. 
    """
    if train_col is not None:
        uniq = train_col.unique()
    else:
        uniq = col.unique()
    name2idx = {o:i for i,o in enumerate(uniq)}
    return name2idx, np.array([name2idx.get(x, -1) for x in col]), len(uniq)

In [26]:
def encode_data(df, train=None):
    """ Encodes rating data with continous user and movie ids. 
    If train is provided, encodes df with the same encoding as train.
    """
    df = df.copy()
    for col_name in ["userId", "movieId"]:
        train_col = None
        if train is not None:
            train_col = train[col_name]
        _,col,_ = proc_col(df[col_name], train_col)
        df[col_name] = col
        df = df[df[col_name] >= 0]
    return df

In [28]:
# encoding the train and validation data
df_train = encode_data(train)
df_valid = encode_data(valid, train)

Matrix factorization model

In [30]:
class MF(nn.Module):
    def __init__(self, num_users, num_items, emb_size=100):
        super(MF, self).__init__()
        self.user_emb = nn.Embedding(num_users, emb_size)
        self.item_emb = nn.Embedding(num_items, emb_size)
        self.user_emb.weight.data.uniform_(0, 0.05)
        self.item_emb.weight.data.uniform_(0, 0.05)
        
    def forward(self, u, v):
        u = self.user_emb(u)
        v = self.item_emb(v)
        return (u*v).sum(1)

In [41]:
# unit testing the architecture

sample = encode_data(train.sample(5))
display(sample)

num_users = 5
num_items = 5
emb_size = 3

user_emb = nn.Embedding(num_users, emb_size)
item_emb = nn.Embedding(num_items, emb_size)
users = torch.LongTensor(sample.userId.values)
items = torch.LongTensor(sample.movieId.values)

U = user_emb(users)
V = item_emb(items)

display(U)

display(U*V) # element wise multiplication

display((U*V).sum(1))

userId  movieId  rating   timestamp
32802       0        0     4.0  1391349194
92302       1        1     5.0   940420585
5142        2        2     5.0   939646939
41616       3        3     4.0  1378497540
5050        2        4     3.0   939647873

tensor([[-0.3881, -1.4092, -0.8383],
        [ 0.9562,  1.0932,  2.2158],
        [-0.1165,  0.3107,  1.0649],
        [-0.2075, -1.0847,  0.6501],
        [-0.1165,  0.3107,  1.0649]], grad_fn=<EmbeddingBackward>)

tensor([[ 0.6496,  0.5128,  1.2918],
        [-0.9693,  0.2661, -0.3521],
        [-0.0077,  0.0638, -0.1173],
        [-0.1759, -2.0299,  0.5365],
        [ 0.0655,  0.0866, -0.0490]], grad_fn=<MulBackward0>)

tensor([ 2.4543, -1.0553, -0.0611, -1.6692,  0.1030], grad_fn=<SumBackward1>)

Model training

In [42]:
num_users = len(df_train.userId.unique())
num_items = len(df_train.movieId.unique())
print(num_users, num_items)

610 8998


In [43]:
model = MF(num_users, num_items, emb_size=100) # .cuda() if you have a GPU

In [44]:
def train_epocs(model, epochs=10, lr=0.01, wd=0.0, unsqueeze=False):
    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=wd)
    model.train()
    for i in range(epochs):
        users = torch.LongTensor(df_train.userId.values) # .cuda()
        items = torch.LongTensor(df_train.movieId.values) #.cuda()
        ratings = torch.FloatTensor(df_train.rating.values) #.cuda()
        if unsqueeze:
            ratings = ratings.unsqueeze(1)
        y_hat = model(users, items)
        loss = F.mse_loss(y_hat, ratings)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        print(loss.item()) 
    test_loss(model, unsqueeze)

In [45]:
def test_loss(model, unsqueeze=False):
    model.eval()
    users = torch.LongTensor(df_valid.userId.values) #.cuda()
    items = torch.LongTensor(df_valid.movieId.values) #.cuda()
    ratings = torch.FloatTensor(df_valid.rating.values) #.cuda()
    if unsqueeze:
        ratings = ratings.unsqueeze(1)
    y_hat = model(users, items)
    loss = F.mse_loss(y_hat, ratings)
    print("test loss %.3f " % loss.item())

In [46]:
train_epocs(model, epochs=10, lr=0.1)

12.911455154418945
4.8501667976379395
2.5946691036224365
3.097404718399048
0.8478994369506836
1.820838212966919
2.6556942462921143
2.134251594543457
1.0896706581115723
0.9762216210365295
test loss 1.850 


In [47]:
train_epocs(model, epochs=15, lr=0.01)

1.6420538425445557
1.004096508026123
0.7115985751152039
0.6606449484825134
0.7254654169082642
0.8037557005882263
0.84348064661026
0.835419237613678
0.7931983470916748
0.7376593351364136
0.6877322793006897
0.655558168888092
0.6444454193115234
0.6495035290718079
0.6609548926353455
test loss 0.821 


In [48]:
train_epocs(model, epochs=15, lr=0.01)

0.6689958572387695
0.6311114430427551
0.6389520168304443
0.614119827747345
0.6051469445228577
0.6136897206306458
0.6114951968193054
0.5966076850891113
0.5845629572868347
0.5827490091323853
0.5838581919670105
0.578920841217041
0.5681834816932678
0.557807207107544
0.5514382719993591
test loss 0.759 


MF with bias

In [49]:
class MF_bias(nn.Module):
    def __init__(self, num_users, num_items, emb_size=100):
        super(MF_bias, self).__init__()
        self.user_emb = nn.Embedding(num_users, emb_size)
        self.user_bias = nn.Embedding(num_users, 1)
        self.item_emb = nn.Embedding(num_items, emb_size)
        self.item_bias = nn.Embedding(num_items, 1)
        self.user_emb.weight.data.uniform_(0,0.05)
        self.item_emb.weight.data.uniform_(0,0.05)
        self.user_bias.weight.data.uniform_(-0.01,0.01)
        self.item_bias.weight.data.uniform_(-0.01,0.01)
        
    def forward(self, u, v):
        U = self.user_emb(u)
        V = self.item_emb(v)
        b_u = self.user_bias(u).squeeze()
        b_v = self.item_bias(v).squeeze()
        return (U*V).sum(1) +  b_u  + b_v

In [50]:
model = MF_bias(num_users, num_items, emb_size=100) #.cuda()

In [51]:
train_epocs(model, epochs=10, lr=0.05, wd=1e-5)

12.912150382995605
9.152730941772461
4.3859100341796875
1.1582977771759033
2.4690911769866943
3.7431256771087646
2.4485058784484863
1.0784105062484741
0.81607985496521
1.318210244178772
test loss 2.069 


In [52]:
train_epocs(model, epochs=10, lr=0.01, wd=1e-5)

1.8935295343399048
1.325158715248108
0.9352132678031921
0.7449430227279663
0.722395658493042
0.777296781539917
0.8227252960205078
0.8217465281486511
0.7813524603843689
0.7275670766830444
test loss 0.798 


In [53]:
train_epocs(model, epochs=10, lr=0.001, wd=1e-5)

0.6853445172309875
0.6711350679397583
0.6592451930046082
0.6494942903518677
0.6416682600975037
0.6355280876159668
0.6308267712593079
0.6273204684257507
0.6247788071632385
0.6229932308197021
test loss 0.751 


Note that these models are susceptible to weight initialization, optimization algorithm and regularization.



### Neural Network Model
Note here there is no matrix multiplication, we could potentially make the embeddings of different sizes. Here we could get better results by keep playing with regularization.

In [54]:
class CollabFNet(nn.Module):
    def __init__(self, num_users, num_items, emb_size=100, n_hidden=10):
        super(CollabFNet, self).__init__()
        self.user_emb = nn.Embedding(num_users, emb_size)
        self.item_emb = nn.Embedding(num_items, emb_size)
        self.lin1 = nn.Linear(emb_size*2, n_hidden)
        self.lin2 = nn.Linear(n_hidden, 1)
        self.drop1 = nn.Dropout(0.1)
        
    def forward(self, u, v):
        U = self.user_emb(u)
        V = self.item_emb(v)
        x = F.relu(torch.cat([U, V], dim=1))
        x = self.drop1(x)
        x = F.relu(self.lin1(x))
        x = self.lin2(x)
        return x

In [55]:
model = CollabFNet(num_users, num_items, emb_size=100) #.cuda()

In [56]:
train_epocs(model, epochs=15, lr=0.05, wd=1e-6, unsqueeze=True)

14.083020210266113
3.1649768352508545
1.2708535194396973
1.793819546699524
1.3548780679702759
1.0356323719024658
1.287137508392334
1.0545822381973267
0.8228969573974609
0.9276160597801208
0.9486841559410095
0.7886616587638855
0.7197826504707336
0.813225269317627
0.7996787428855896
test loss 0.779 


In [57]:
train_epocs(model, epochs=10, lr=0.001, wd=1e-6, unsqueeze=True)

0.696186363697052
0.6877015829086304
0.6879603862762451
0.6886828541755676
0.6885420083999634
0.6869543194770813
0.6834055185317993
0.6828559637069702
0.6811237931251526
0.6824584603309631
test loss 0.763 


In [58]:
train_epocs(model, epochs=10, lr=0.001, wd=1e-6, unsqueeze=True)

0.6813802123069763
0.6804739236831665
0.68137127161026
0.6783655285835266
0.6785134673118591
0.6774048805236816
0.6747931838035583
0.6761834025382996
0.673831045627594
0.673130214214325
test loss 0.755 


### Neural network model - different approach
Ref - [T Abhishek](https://youtu.be/MVB1cbe923A)

In [ ]:
!pip install tez

In [66]:
import pandas as pd
import tez

In [ ]:
df = pd.read_csv("./data/MovieLens_LatestSmall_ratings.csv.csv")
df.head()

Rest of the code is already written by the author and will be available soon.